inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
  - "Gemfile"
  - "Rakefile"
  - "bin/**/*"
  - "spec/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
